server:
  port: 8081
spring:
  application:
    name: "load-system"
  datasource:
    url: "jdbc:postgresql://database-1.cn8see6oisrh.us-east-1.rds.amazonaws.com:5432/postgres"
    username: "postgres"
    password: "S7k~kOo|I,02:,z9]841"
    driverClassName: "org.postgresql.Driver"
  jpa:
    #hibernate:
      #ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    open-in-view: false
  data:
    mongodb:
      uri: "mongodb+srv://dbuser:DMekHRirbSkdNyfj@cluster0.s4e6i.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
jwt:
  secret: secretsecretsecretsecretsecretsecretsecretsecretsecret
load-system:
  email:
    sender: corporate@betbillions.com.co
    password: Fara4020**
