server:
  port: 5000
spring:
  thymeleaf:
    check-template-location: false
  application:
    name: "load-system"
  datasource:
    url: "${DATABASE}"
    username: "${USER}"
    password: "${PASSWORD}"
    driverClassName: "org.postgresql.Driver"
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        hbm2ddl:
          auto: update
    open-in-view: false
  data:
    mongodb:
      uri: "${MONGO}"
jwt:
  secret: e9f5c7e85b1f6d9df7d8e8d4c3b5a1a0e6f9d7c2e4b5a8d3f6b1e3c7a4d2f9b8
load-system:
  email:
    sender: Cashrdmoney@gmail.com
    password: aesweghbwgkkkxmk
aws:
  bucketName: "${BUCKET}"
  accessKey: "${ACCESS}"
  secretKey: "${SECRET}"





